#!/usr/bin/env node
/* eslint-disable */
/**
 * Full-body static pre-rendering (runs as part of the "postbuild" npm script,
 * immediately after scripts/prerender-meta.js).
 *
 * WHY NOT react-snap
 * ------------------
 * react-snap was evaluated first. It installs and its bundled Chromium 78 does
 * launch, but it is the wrong tool for this repo:
 *
 *   - It rewrites <head>: inlineCss / minimalcss / minifyHtml / removeStyleTags
 *     / preloadImages. This project's <head> is generated by prerender-meta.js
 *     and already passes 60 audit checks (exactly one canonical, robots, OG set
 *     and JSON-LD block per route). Handing that to react-snap means either
 *     duplicated tags (shell + Helmet) or losing the audited output.
 *   - Readiness is a fixed `waitFor` delay. There is no hook for a real
 *     "page is ready" signal, and a guessed delay is not an acceptable
 *     correctness mechanism for 131 routes.
 *   - Routes come from link crawling / a hand-listed `include` array, which
 *     would be a second route list competing with prerender-meta.js.
 *   - puppeteer ^1.8.0 (2018), flagged by npm as no longer supported.
 *
 * WHAT THIS DOES INSTEAD
 * ----------------------
 * Drives Chromium directly and injects ONLY the rendered #root markup into the
 * route HTML that prerender-meta.js already wrote. Consequences worth stating:
 *
 *   - <head> is never touched, so the audited metadata survives byte-for-byte.
 *   - Anything outside #root in the shell is left alone.
 *   - A route that fails keeps its head-only HTML — it degrades to the previous
 *     behaviour rather than shipping a broken page — and is reported.
 *   - The route list comes from .prerender-routes.json, written by
 *     prerender-meta.js, so there is one owner of "which URLs exist".
 *
 * Private routes (login / dashboard / ai-studio / lead inbox) are never
 * pre-rendered: they have no entry in the manifest and keep using the SPA
 * fallback plus their X-Robots-Tag header.
 *
 * Readiness is the app's own signal: window.__PRERENDER_READY__, set by <Seo>
 * once the route's React.lazy chunk has resolved and committed. The timeout is
 * a failure path, not the mechanism.
 */
const fs = require('fs');
const http = require('http');
const path = require('path');

const BUILD_DIR = path.join(__dirname, '..', 'build');
const MANIFEST = path.join(__dirname, '..', '.prerender-routes.json');

const PORT = Number(process.env.PRERENDER_PORT || 45678);
const NAV_TIMEOUT_MS = Number(process.env.PRERENDER_NAV_TIMEOUT || 30000);
const READY_TIMEOUT_MS = Number(process.env.PRERENDER_READY_TIMEOUT || 60000);
const CONCURRENCY = Number(process.env.PRERENDER_CONCURRENCY || 4);

// Only the DOM is being captured, never the pixels, so images, media and fonts
// are dropped at the network layer. Their markup (src, width, height, loading,
// alt) is untouched — it is already in the DOM before the byte arrives. This is
// also what keeps the run honest: /products references 94 product images, and
// fetching them all across parallel pages was starving the main thread badly
// enough that the readiness signal missed its deadline.
//
// Stylesheets and scripts are NOT blocked: layout drives the
// IntersectionObserver gating in LivingGallery, so removing CSS would change
// what renders.

/* ── skip switch, so a broken Chromium can never block a release ─── */
if (process.env.SKIP_PRERENDER_BODY === '1') {
  console.log('[prerender-body] SKIP_PRERENDER_BODY=1 — leaving head-only HTML in place');
  process.exit(0);
}

/**
 * Degrade instead of failing when no browser is available.
 *
 * This step needs headless Chrome. Shared hosting (Hostinger, cPanel and
 * friends) generally cannot run it — Puppeteer installs, but the Chrome binary
 * is missing or the libraries it needs are not on the box. Failing the build
 * there would block a deploy over an optimisation, so the missing-browser case
 * exits 0 and leaves the head-only HTML that prerender-meta.js already wrote:
 * exactly the behaviour the site had before this step existed.
 *
 * It is loud rather than silent, and `npm run seo:audit` still fails on the
 * resulting empty bodies, so a degraded build cannot be mistaken for a good
 * one. Set PRERENDER_REQUIRED=1 in CI to make it a hard error.
 */
const REQUIRED = process.env.PRERENDER_REQUIRED === '1';

function degrade(reason, hint) {
  const level = REQUIRED ? console.error : console.warn;
  level(`[prerender-body] SKIPPED — ${reason}`);
  if (hint) level(`[prerender-body] ${hint}`);
  level(
    '[prerender-body] Route HTML keeps its correct <head> (title, canonical, OG, JSON-LD)\n' +
      '[prerender-body] but ships an empty <body> — crawlers get metadata, not page content.\n' +
      '[prerender-body] Build where a browser exists (locally or in CI) and deploy build/.'
  );
  process.exit(REQUIRED ? 1 : 0);
}

let puppeteer;
try {
  puppeteer = require('puppeteer');
} catch (e) {
  degrade(
    'puppeteer is not installed',
    'It is a devDependency, so `npm ci --omit=dev` / NODE_ENV=production skips it.'
  );
}

if (!fs.existsSync(MANIFEST)) {
  console.error('[prerender-body] .prerender-routes.json missing — prerender-meta.js must run first.');
  process.exit(1);
}
const { routes } = JSON.parse(fs.readFileSync(MANIFEST, 'utf8'));

/* ── static server over build/ (mirrors the .htaccess order) ─────── */
const TYPES = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'application/javascript',
  '.css': 'text/css',
  '.json': 'application/json',
  '.xml': 'application/xml',
  '.txt': 'text/plain',
  '.webp': 'image/webp',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.svg': 'image/svg+xml',
  '.woff2': 'font/woff2',
  '.pdf': 'application/pdf',
  '.mp4': 'video/mp4',
  '.ico': 'image/x-icon',
};

const server = http.createServer((req, res) => {
  const urlPath = decodeURIComponent(req.url.split('?')[0]);
  const clean = urlPath.replace(/^\/+/, '').replace(/\/+$/, '');

  const asFile = path.join(BUILD_DIR, clean);
  if (clean && fs.existsSync(asFile) && fs.statSync(asFile).isFile()) {
    res.writeHead(200, { 'Content-Type': TYPES[path.extname(asFile)] || 'application/octet-stream' });
    return res.end(fs.readFileSync(asFile));
  }
  // Serve an EMPTY shell for route paths, never the route's own head-only file:
  // the app must render the route from scratch, not hydrate a snapshot of
  // itself. .prerender-shell.html is the pristine react-scripts output that
  // prerender-meta.js snapshotted; app-shell.html is the same thing with a
  // noindex head. index.html is the last resort and only correct before this
  // script has injected the homepage into it.
  const shell = [
    path.join(__dirname, '..', '.prerender-shell.html'),
    path.join(BUILD_DIR, 'app-shell.html'),
    path.join(BUILD_DIR, 'index.html'),
  ].find((p) => fs.existsSync(p));
  res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' });
  return res.end(fs.readFileSync(shell));
});

/* ── capture one route ───────────────────────────────────────────── */
async function capture(browser, route) {
  const page = await browser.newPage();
  const consoleErrors = [];
  try {
    await page.setViewport({ width: 1440, height: 900 });
    // Flag the environment BEFORE any app code runs, so <Seo> knows to emit the
    // readiness signal and LandingPage knows to freeze the hero carousel.
    await page.evaluateOnNewDocument(() => {
      window.__PRERENDER__ = true;
      window.__PRERENDER_READY__ = false;
    });

    // Images are switched off in Blink (see the launch flags), not per request:
    // interception costs a JS round-trip on every asset and took this run from
    // 89s to 723s. Anything the disabled loader still complains about is this
    // script's own doing, so those lines are filtered out — otherwise every
    // route reports errors and a real one would be invisible.
    const isAssetNoise = (text) =>
      /Failed to load resource|net::ERR_|ERR_BLOCKED|Failed to fetch|blocked by CORS/i.test(
        text
      );

    page.on('console', (msg) => {
      if (msg.type() !== 'error') return;
      const text = msg.text();
      if (!isAssetNoise(text)) consoleErrors.push(text);
    });
    page.on('pageerror', (err) => consoleErrors.push(`pageerror: ${err.message}`));

    const url = `http://127.0.0.1:${PORT}${route.path}`;
    await page.goto(url, { waitUntil: 'domcontentloaded', timeout: NAV_TIMEOUT_MS });

    // Deterministic readiness: the app tells us when the route committed.
    await page.waitForFunction('window.__PRERENDER_READY__ === true', {
      timeout: READY_TIMEOUT_MS,
      polling: 50,
    });

    const result = await page.evaluate(() => {
      const root = document.getElementById('root');
      if (!root) return null;
      return {
        html: root.innerHTML,
        text: (root.textContent || '').replace(/\s+/g, ' ').trim(),
        h1: Array.from(root.querySelectorAll('h1')).map((h) => h.textContent.trim()),
        h2Count: root.querySelectorAll('h2').length,
        linkCount: root.querySelectorAll('a[href]').length,
        imgCount: root.querySelectorAll('img').length,
        hasFooter: Boolean(root.querySelector('footer')),
        hasMain: Boolean(root.querySelector('main')),
      };
    });

    if (!result || !result.html.trim()) {
      return { route, ok: false, reason: '#root rendered empty' };
    }
    if (result.text.length < 200) {
      return { route, ok: false, reason: `only ${result.text.length} chars of text` };
    }

    return { route, ok: true, ...result, consoleErrors };
  } catch (err) {
    return { route, ok: false, reason: err.message.split('\n')[0], consoleErrors };
  } finally {
    await page.close().catch(() => {});
  }
}

/* ── inject the captured body into the existing route HTML ───────── */
function injectBody(routePath, bodyHtml) {
  const file =
    routePath === '/'
      ? path.join(BUILD_DIR, 'index.html')
      : path.join(BUILD_DIR, routePath, 'index.html');
  if (!fs.existsSync(file)) return { ok: false, reason: 'route HTML missing' };

  let html = fs.readFileSync(file, 'utf8');

  // Only the empty #root is replaced. The <head> — and everything else outside
  // #root — is left exactly as prerender-meta.js wrote it.
  const rootRe = /(<div id="root">)(\s*)(<\/div>)/;
  if (!rootRe.test(html)) return { ok: false, reason: 'no empty #root to fill' };
  html = html.replace(rootRe, (_m, open, _ws, close) => `${open}${bodyHtml}${close}`);

  // A pre-rendered page has content in the HTML, so the splash overlay has
  // nothing to cover — and as a fixed, full-viewport white layer it would sit
  // over that content for any client that doesn't run the JS which removes it.
  // Dropping it here also takes it off the LCP path. App.js's dismissSplash
  // already no-ops when the node is absent, and the plain shell keeps its
  // splash for the SPA-fallback routes.
  // Matched up to the #root lookahead rather than to a closing tag: the splash
  // contains nested divs, so a lazy `</div>` stops at the first inner one and
  // silently removes nothing.
  html = html.replace(/<div id="tirich-splash">[\s\S]*?(?=<div id="root">)/, '');

  fs.writeFileSync(file, html, 'utf8');
  return { ok: true, bytes: Buffer.byteLength(html) };
}

/* ── run ─────────────────────────────────────────────────────────── */
(async () => {
  const started = Date.now();
  await new Promise((resolve, reject) => {
    server.listen(PORT, '127.0.0.1', resolve);
    server.on('error', reject);
  });

  // Fail fast and clearly if the browser binary is absent, rather than letting
  // the error surface as 107 route failures. executablePath() is sync in some
  // Puppeteer versions and a promise in others, so await covers both; anything
  // unexpected falls through to launch(), whose catch handles it.
  try {
    const exe = await puppeteer.executablePath();
    if (typeof exe === 'string' && exe && !fs.existsSync(exe)) {
      throw new Error(`Chrome binary not found at ${exe}`);
    }
  } catch (e) {
    await new Promise((r) => server.close(r));
    degrade(
      `no Chrome binary available (${e.message.split('\n')[0]})`,
      'Install it with `npx puppeteer browsers install chrome`, or set ' +
        'PUPPETEER_EXECUTABLE_PATH to an existing Chrome/Chromium.'
    );
  }

  const browser = await puppeteer.launch({
    args: [
      '--no-sandbox',
      '--disable-setuid-sandbox',
      '--disable-dev-shm-usage',
      // Only the DOM is captured, never the pixels. Image markup (src, alt,
      // width, height, loading) is in the DOM before any byte arrives, so the
      // output HTML is identical — this just stops 94 product images per
      // catalogue page from starving the main thread and pushing the
      // readiness signal past its deadline.
      '--blink-settings=imagesEnabled=false',
      '--disable-remote-fonts',
      '--mute-audio',
      // Fail every non-local hostname at DNS instead of over the network.
      // App.js kicks off a background /auth/me call on mount, so without this
      // the pre-render fires 107 real requests at the production API and waits
      // on each CORS rejection. Google Fonts goes the same way. Nothing outside
      // this machine is needed to render a route: the catalogue is bundled.
      '--host-resolver-rules=MAP * ~NOTFOUND, EXCLUDE 127.0.0.1',
    ],
  });

  const succeeded = [];
  const failed = [];
  const stats = [];

  // Small worker pool — 131 sequential page loads is needlessly slow, and
  // unbounded parallelism starves Chromium.
  const record = (route, res) => {
    const injected = injectBody(route.path, res.html);
    if (!injected.ok) return injected.reason;
    succeeded.push(route.path);
    stats.push({
      path: route.path,
      text: res.text.length,
      h1: res.h1.length,
      links: res.linkCount,
      footer: res.hasFooter,
      errors: res.consoleErrors.length,
    });
    return null;
  };

  const queue = [...routes];
  const retryQueue = [];
  await Promise.all(
    Array.from({ length: Math.min(CONCURRENCY, queue.length) }, async () => {
      while (queue.length) {
        const route = queue.shift();
        const res = await capture(browser, route);
        if (!res.ok) {
          retryQueue.push({ route, reason: res.reason });
          continue;
        }
        const reason = record(route, res);
        if (reason) retryQueue.push({ route, reason });
      }
    })
  );

  // Second pass, strictly sequential. The parallel pass competes for one main
  // thread, so a heavy route can miss the readiness deadline through no fault
  // of its own; retrying it alone distinguishes contention from a real failure.
  if (retryQueue.length) {
    console.log(`[prerender-body] retrying ${retryQueue.length} route(s) sequentially…`);
    for (const { route, reason: firstReason } of retryQueue) {
      const res = await capture(browser, route);
      if (!res.ok) {
        failed.push({ path: route.path, reason: `${res.reason} (first attempt: ${firstReason})` });
        continue;
      }
      const reason = record(route, res);
      if (reason) failed.push({ path: route.path, reason });
    }
  }

  await browser.close();
  await new Promise((r) => server.close(r));

  /* ── report ─────────────────────────────────────────────────────── */
  const secs = ((Date.now() - started) / 1000).toFixed(1);
  const withErrors = stats.filter((s) => s.errors > 0);
  const noH1 = stats.filter((s) => s.h1 !== 1);
  const noFooter = stats.filter((s) => !s.footer);
  const median = (arr) => {
    if (!arr.length) return 0;
    const s = [...arr].sort((a, b) => a - b);
    return s[Math.floor(s.length / 2)];
  };

  console.log(
    `[prerender-body] ${succeeded.length}/${routes.length} routes given a full body in ${secs}s ` +
      `(median ${median(stats.map((s) => s.text))} chars of text, ` +
      `${median(stats.map((s) => s.links))} internal links)`
  );
  if (noH1.length) {
    console.log(
      `[prerender-body] ${noH1.length} route(s) without exactly one <h1>: ` +
        noH1.slice(0, 5).map((s) => `${s.path} (${s.h1})`).join(', ')
    );
  }
  if (noFooter.length) {
    console.log(`[prerender-body] ${noFooter.length} route(s) without a <footer>: ` +
      noFooter.slice(0, 5).map((s) => s.path).join(', '));
  }
  if (withErrors.length) {
    console.log(
      `[prerender-body] ${withErrors.length} route(s) logged console errors during capture: ` +
        withErrors.slice(0, 5).map((s) => s.path).join(', ')
    );
  }
  if (failed.length) {
    console.error(`[prerender-body] ${failed.length} route(s) FAILED (left head-only):`);
    for (const f of failed.slice(0, 15)) console.error(`  ${f.path} — ${f.reason}`);
    process.exit(1);
  }

  fs.rmSync(MANIFEST, { force: true });
})().catch((err) => {
  const msg = err.message || String(err);
  // "Could not find Chrome", missing shared libraries, no sandbox available —
  // all environment problems, not build problems. Degrade rather than block.
  if (/Could not find (Chrome|Chromium)|Failed to launch|error while loading shared libraries|ENOENT.*chrome/i.test(msg)) {
    degrade(`Chrome could not start (${msg.split('\n')[0]})`,
      'Shared hosting usually cannot run headless Chrome at all.');
  }
  console.error('[prerender-body] fatal:', msg);
  process.exit(1);
});
